scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test the CRs
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_meteringreceiver_cr.yaml"
    # `olm` tests configured to test the CRs
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_v1alpha1_meteringreceiver_cr.yaml"
        csv-path: "deploy/olm-catalog/ibm-metering-receiver-operator/3.7.0/ibm-metering-receiver-operator.v3.7.0.clusterserviceversion.yaml"
