apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-metering-receiver-operator
  labels:
    app.kubernetes.io/instance: "ibm-metering-receiver-operator"
    app.kubernetes.io/managed-by: "ibm-metering-receiver-operator"
    app.kubernetes.io/name: "ibm-metering"
